# Generated by Django 5.0.7 on 2024-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0002_rename_category_id_product_sub_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(upload_to='SubCategory'),
        ),
    ]
