# Generated by Django 5.0.7 on 2024-08-01 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0003_alter_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_shop.subcategory'),
        ),
    ]
