# Generated by Django 5.0.7 on 2024-10-30 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0007_alter_productvariant_color_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_shop.productvariant'),
        ),
    ]
